---
opa_old_versions:
  - 0.4
opa_version: 0.5
k8s_config: |
  "exec-opts": ["native.cgroupdriver=systemd"],
  "icc": false,
  "live-restore": true,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "200"
  },
  "userland-proxy": false,
  "no-new-privileges": true,
  "experimental": true
k8s_nv_config: |
  "runtimes": {
  "nvidia": {
    "path": "nvidia-container-runtime",
    "runtimeArgs": []
    }
  },
  "default-runtime": "nvidia"
