- name: "Set {{ item.option }} to {{ item.value }} in {{ item.file }}.conf"
  ini_file:
    path: "/etc/sysctl.d/{{ item.file }}.conf"
    section: null
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  notify: Reload sysctl
