- name: Deploy WireGuard generator config
  template:
    src: wg-gen.conf.j2
    dest: /etc/wireguard/wg-gen.conf
    owner: root
    group: root
    mode: '0600'

- name: Deploy WireGuard generator
  copy:
    src: wg-gen.sh
    dest: /etc/wireguard/wg-gen.sh
    owner: root
    group: root
    mode: '0755'

# TODO idempotency
- name: Generate WireGuard config
  command: /etc/wireguard/wg-gen.sh

- name: Enable WireGuard
  systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: yes

- include_role:
    name: firewalld
  loop:
  - { service: 'wireguard', port: "{{ wg_port }}/udp" }

- name: Enable firewalld masqueare
  shell:
    cmd: firewall-cmd --add-masquerade --permanent && firewall-cmd --reload
  register: fw_mq
  changed_when: (fw_mq_str not in fw_mq.stderr)

# TODO other options https://www.cyberciti.biz/faq/centos-8-set-up-wireguard-vpn-server/
- include_role:
    name: sysctl
  loop:
  - { file: '99-wireguard', option: 'net.ipv4.ip_forward', value: '1' }
  - { file: '99-wireguard', option: 'net.ipv6.conf.all.forwarding', value: '1' }
