# TODO working setup: host-installed toolkit, pod-installed driver
# desired setup: host-installed toolkit + driver
# till then, remove driver/cuda and install toolkit here
- name: Check if any NV package is present
  shell:
    cmd: apt list --installed | grep -E 'nvidia|cuda' | grep -v 'nvidia-container'
  failed_when: no
  changed_when: no
  register: nv_cuda_pkg

- include_role:
    name: nvpurge
  when: nv_cuda_pkg.rc == 0

- include_role:
    name: 3rdparty
  loop:
  - { name: 'NVIDIA Container Toolkit', gpg_url: 'https://nvidia.github.io/nvidia-docker/gpgkey', repo_file: 'nvidia-docker', package: "{{ packages }}" }
  vars:
    packages:
    - nvidia-container-toolkit
    - nvidia-container-runtime
# END TODO

- name: Install containerd
  apt:
    name: containerd
    state: latest

- name: Enable containerd
  systemd:
    name: containerd.service
    state: started
    enabled: yes

- name: Disable Nouveau driver
  copy:
    src: blacklist-nouveau.conf
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    mode: '0644'
  notify: Update initramfs

- name: Load GPU operator dependency modules
  modprobe:
    name: "{{ item }}"
  loop: "{{ gpuop_modules }}"

- name: Load GPU Operator dependency modules on boot
  lineinfile:
    path: /etc/modules-load.d/gpuop.conf
    line: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
    create: yes
  loop: "{{ gpuop_modules }}"
