- name: Install the containerd==1.5.2 packages
  apt:
    state: present
    name: containerd=1.5.2-0ubuntu1~20.04.3
    force: yes

- name: Prevent containerd from being upgraded
  dpkg_selections:
    name: containerd
    selection: hold

- name: Enable containerd
  systemd:
    name: containerd.service
    state: started
    enabled: yes

- name: Disable Nouveau driver
  copy:
    src: blacklist-nouveau.conf
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    mode: '0644'
  notify: Update initramfs

- name: Load GPU operator dependency modules
  modprobe:
    name: "{{ item }}"
  loop: "{{ gpuop_modules }}"

- name: Load GPU Operator dependency modules on boot
  lineinfile:
    path: /etc/modules-load.d/gpuop.conf
    line: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
    create: yes
  loop: "{{ gpuop_modules }}"
