- include_role:
    name: docker

# TODO figure out how to get K8s to work w/ active firewall
# till then it's pointless to add rules that'll be unused
#- include_tasks: firewall.yml
- include_tasks: install.yml
