- name: Install perf
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - linux-tools-common
    - "linux-generic-hwe-{{ ubuntu_version }}-edge"

# https://www.jetbrains.com/help/clion/cpu-profiler.html
- include_role:
    name: sysctl
  loop:
  - { file: '99-perf', option: 'kernel.perf_event_paranoid', value: '1' }
  - { file: '99-perf', option: 'kernel.kptr_restrict', value: '0' }
