- name: Remove conflicting NoMachine Enterprise Client
  apt:
    name: nomachine-enterprise-client
    state: absent

# gotta install firewalld, as we need to flush before adding the service
- name: Install firewalld
  apt:
    name: firewalld
    state: latest

# install the package separately for easy register
- include_role:
    name: 3rdparty
  loop:
  - { name: 'NoMachine Enterprise Desktop', gpg_url: 'https://apt.noobient.com/files/noobuntu.asc', repo_file: 'noobuntu', package: 'nomachine-enterprise-desktop' }

# installing NX adds temporary ports to public zone
# thirdparty_install is the variable registered by 3rdparty
- name: Restart firewalld to flush temporary ports
  systemd:
    name: firewalld
    state: restarted
  when: thirdparty_install.changed

- include_role:
    name: firewalld
  loop:
  - { service: 'nomachine', port: '4000/tcp' }
  - { service: 'nomachine', port: '4080/tcp' }
  - { service: 'nomachine', port: '4443/tcp' }
  - { service: 'nomachine', port: '5353/udp' }

- name: Enable NoMachine service
  systemd:
    name: nxserver
    state: started
    enabled: yes

# applies to all new sessions, no restart necessary
# https://www.nomachine.com/AR04K00663
# virtual desktops are not supported in Enterprise Desktop
- name: Allow NX connections without interactive approval
  lineinfile:
    path: /usr/NX/etc/server.cfg
    line: 'PhysicalDesktopAuthorization 0'
    regexp: '^PhysicalDesktopAuthorization '
