- name: Install cifs-utils
  yum:
    name: cifs-utils
    state: latest
  when: ansible_distribution == 'CentOS'

- name: Install cifs-utils
  apt:
    name: cifs-utils
    state: latest
  when: ansible_distribution == 'Ubuntu'
