# https://unix.stackexchange.com/a/345518/88217
# example mount point: /mnt/foo, then the unit file becomes mnt-foo.mount, so
# assume the first character is /, skip it, and replace the remaining slashes
# with dashes
- set_fact:
    smb_unit: "{{ item.mountpoint[1:] | replace('/','-') }}"

- name: "Add mounts for {{ item.host }}.{{ ad_domain }}/{{ item.path }} as {{ item.mountpoint }}"
  template:
    src: foo.mount.j2
    dest: "/etc/systemd/system/{{ smb_unit }}.mount"

- name: "Add auto-mounts for {{ item.host }}.{{ ad_domain }}/{{ item.path }}"
  copy:
    src: foo.automount
    dest: "/etc/systemd/system/{{ smb_unit }}.automount"

- name: "Enable auto-mounts for {{ item.host }}.{{ ad_domain }}/{{ item.path }}"
  systemd:
    enabled: yes
    state: started
    daemon_reload: yes
    name: "{{ smb_unit }}.automount"
