- name: Reload AppArmor profiles
  systemd:
    name: apparmor
    state: reloaded

- name: Compile GLib schema
  command: glib-compile-schemas /usr/share/glib-2.0/schemas

- name: Update PAM auth
  command: "{{ item }}"
  with_items:
  - pam-auth-update --enable fscrypt
  - pam-auth-update --enable keyinit-fix

- name: Update GRUB
  shell: update-grub

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: Restart Defender ATP
  systemd:
    name: mdatp
    state: restarted
