- include_role:
    name: 3rdparty
  loop:
  - { name: 'Docker', gpg_url: 'https://download.docker.com/linux/ubuntu/gpg', repo_file: 'docker', package: "{{ packages }}" }
  vars:
    packages:
    - docker-ce
    - docker-ce-cli

- include_tasks: nv_runtime.yml
  when: k8s_nv_node is defined and k8s_nv_node == True

- include_tasks: opa.yml
  when: ((k8s_node is not defined) or (k8s_node is defined and k8s_node != True)) and ((k8s_nv_node is not defined) or (k8s_nv_node is defined and k8s_nv_node != True))
