- hosts: "{{ target | default('127.0.0.1') }}"
  connection: "{% if target is defined %}ssh{% else %}local{% endif %}"
  become: yes
  module_defaults:
    apt:
      force_apt_get: yes
  roles:
  - update
  - { role: networkmanager, when: ansible_distribution == 'Ubuntu' }
  - { role: nofirstrun, when: ansible_distribution == 'Ubuntu' }
  - ad
