---
#- include_tasks: repo.yml
# TODO extend to EL
- include_tasks: release.yml
  when: ansible_distribution == 'Ubuntu'
# TODO enable for 20.04 once applicable
- include_tasks: hwe.yml
  when: (ansible_distribution == 'Ubuntu') and (ansible_distribution_version == '18.04')

- include_tasks: ansible.yml

- include_tasks: update_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- include_tasks: update_el7.yml
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '7')
- include_tasks: update_el8.yml
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '8')
