- name: Deploy APT maintenance job
  copy:
    src: apt-maintenance
    dest: /etc/cron.daily/apt-maintenance
    mode: '0755'
  notify: Restart cron service
  when: no_apt_maintenance is not defined

- name: Remove APT maintenance job
  file:
    path: /etc/cron.daily/apt-maintenance
    state: absent
  notify: Restart cron service
  when: no_apt_maintenance is defined

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: no

- name: Update all packages
  apt:
    upgrade: dist
    update_cache: no

- name: Remove obsolete packages
  apt:
    autoremove: yes
