- name: Deploy APT maintenance job
  copy:
    src: apt-maintenance
    dest: /etc/cron.daily/apt-maintenance
    mode: '0755'
  notify: Restart cron service

- name: Update apt info and all OS packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Remove obsolete packages
  apt:
    autoremove: yes
