- name: Update yum info and all OS packages
  yum:
    name: '*'
    state: latest

- name: Install dnf-automatic
  yum:
    name: dnf-automatic

- name: Enable automatic updates
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: yes
