- name: Install AD prerequisites
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - sssd
    - sssd-tools
    - libsss-sudo
    - realmd
    - libnss-sss
    - libpam-sss
    - adcli
    - samba-common-bin
    - krb5-user
    - packagekit
  when: ansible_distribution == 'Ubuntu'

- name: Install AD prerequisites
  yum:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - sssd-ad
    - krb5-workstation
    - oddjob-mkhomedir
    - samba-common-tools
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: Install AD prerequisites
  yum:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - authselect
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and (ansible_distribution_major_version == '8')
