# this should work regardless of unit path or service state
- name: Check if SSSD service is present
  shell: systemctl cat sssd.service
  ignore_errors: yes
  changed_when: no
  no_log: True
  register: sssd_service

- name: Ensure SSSD conf.d directory exists
  file:
    state: directory
    path: /etc/sssd/conf.d
    recurse: yes
  when: sssd_service.rc == 0

- name: Set up SSSD options
  ini_file:
    path: "/etc/sssd/conf.d/{{ item.file }}.conf"
    owner: root
    group: root
    mode: '0600'
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  when: sssd_service.rc == 0
  register: sssd_opts

# TODO keytab doesn't exist until domain joined and SSSD fails to start without it on 20.04
- name: Check Kerberos keytab
  stat:
    path: /etc/krb5.keytab
  register: krb5_keytab

- name: Restart SSSD
  systemd:
    name: sssd.service
    state: restarted
  when: (sssd_opts is defined) and (sssd_opts.changed) and (krb5_keytab.stat.exists == True)
