# this should work regardless of unit path or service state
- name: Check if SSSD service is present
  shell: systemctl cat sssd.service
  ignore_errors: yes
  changed_when: no
  no_log: True
  register: sssd_service

- include_tasks: confd.yml
  when: sssd_service.rc == 0
