# this should work regardless of unit path or service state
- name: Check if SSSD service is present
  shell: systemctl cat sssd.service
  failed_when: no
  changed_when: no
  register: sssd_service

- include_tasks: confd.yml
  when: sssd_service.rc == 0
