- name: Fix snaps in non-default home
  lineinfile:
    path: /etc/apparmor.d/tunables/home.d/corporate
    line: '@{HOMEDIRS}+=/home/{{ ad_domain }}/'
    create: yes
    mode: '0644'
  notify: Reload AppArmor profiles
