---
- include_role:
    name: secureboot

# TODO decide if we want the PPA stuff or not
#- include_tasks: repo_ppa.yml
- include_tasks: repo_main.yml
  when: cuda_runfile_install == True
- include_tasks: repo_cuda.yml
  when: cuda_runfile_install != True

- include_tasks: driver.yml

- include_role:
    name: 3rdparty
  loop:
  - { name: 'NVIDIA Container Toolkit', gpg_url: 'https://nvidia.github.io/nvidia-docker/gpgkey', repo_file: 'nvidia-docker', package: "{{ packages }}" }
  vars:
    packages:
    - nvidia-container-toolkit
    - nvidia-container-runtime
