# need to manually remove old version AND its dependencies
# also libnvidia packages, some switches may cause older versions
# to be available in the repo, causing a conflict

#- name: Uninstall mismatching NV packages
#  apt:
#    name: "{{ packages }}"
#    state: absent
#    autoremove: yes
#  vars:
#    packages:
#    - "nvidia-driver-*"
#    - "nvidia-*"
#    - "libnvidia-*"
#    - "libxnvctrl0"
#    - "libnvinfer*"
#    - "xserver-xorg-video-nvidia*"
#    - "tensorrt*"
#    - "cuda-*"

# the above command sometime files even though it's supposed to be equivalent, so let's do it manually
# rc=100 when apt didn't find any package to remove, that's fine

# These may or may not be available, they are not in the CUDA repo.
# But when they are installed, they must be purged first, otherwise the other purge fails.
- name: Uninstall optional NV libs
  shell: apt purge -y --autoremove "libnvparsers*" "libnvonnxparsers*"
  ignore_errors: yes
  no_log: True

- name: Uninstall mismatching NV packages
  shell: apt purge -y --autoremove "nvidia-*" "libnvidia-*" "libxnvctrl0" "libnvinfer*" "xserver-xorg-video-nvidia*" "tensorrt*" "cuda-*"
  register: nv_purge
  failed_when: (nv_purge.rc != 0) and (nv_purge.rc != 100)
