- name: Remove CUDA repo
  file:
    path: "/etc/apt/sources.list.d/cuda.list"
    state: absent
  register: cuda_driver

- include_tasks: purge_driver.yml
  when: cuda_driver.changed

- name: Add graphics drivers PPA
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    mode: '0644'
