- name: Remove graphics-driver PPA
  file:
    path: "/etc/apt/sources.list.d/ppa_graphics_drivers_ppa_{{ ubuntu_codename }}.list"
    state: absent
  register: ppa_driver

- name: Add NVIDIA CUDA repo apt preferences
  template:
    src: nvidia.j2
    dest: /etc/apt/preferences.d/nvidia
    mode: '0644'
  register: cuda_driver

- include_tasks: purge_driver.yml
  when: ppa_driver.changed or cuda_driver.changed

- name: Import CUDA repo GPG key
  apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    state: present

- name: Add CUDA repo
  copy:
    src: cuda.list
    dest: /etc/apt/sources.list.d/cuda.list
    mode: '0644'
