- include_tasks: install.yml
  when: installed_firewalld is not defined
# a zone is pointless without a source defined
- include_tasks: zone.yml
  when: (zone is defined) and (source is defined) and (k8s_node is not defined)
- include_tasks: service.yml
  when: (service is defined) and (k8s_node is not defined)
