- name: "Create {{ zone }} firewall zone"
  shell: "firewall-cmd --permanent --new-zone={{ zone }} && firewall-cmd --reload"
  register: fw_new_zone
  failed_when: (fw_new_zone.rc != 0) and (fw_zone_str not in fw_new_zone.stderr)
  changed_when: ('success' in fw_new_zone.stdout)

- name: "Add {{ source }} as source in {{ zone }} zone"
  shell: "firewall-cmd --zone={{ zone }} --add-source={{ source }} --permanent && firewall-cmd --reload"
  register: fw_add_src
  changed_when: (fw_src_str not in fw_add_src.stderr)
